### ISSUE TITLE
HDF5.jl API has changed and sparse matrix has changed.

### ISSUE THREAD

**Issue by russelljjarvis** [rikenbit/OnlinePCA.jl#13]
Hey awesome package!

HDF5.jl API has changed and sparse matrix has changed.

Minor fixes seem to help: see for example: https://github.com/rikenbit/OnlinePCA.jl/pull/12

Note I don't necessarily endorse the merge, just showing its a minor fix.

**Comment by kokitsuyuzaki** [comment]
Hi, @russelljjarvis 
Thanks for fixing my package!
To keep this working environment fixed, I've deployed the Docker image to the GHCR, so next time it stops working, try this one.
https://github.com/rikenbit/OnlinePCA.jl/pkgs/container/onlinepcajl

**Comment by russelljjarvis** [comment]
AOK thanks. 

Hi @kokitsuyuzaki, I was trying to apply your package Online PCA to 1million cells spike train data like this:

![image](https://user-images.githubusercontent.com/7786645/172101213-e262ff1b-f6ea-446d-a241-51d38dc17396.png)

I wanted to reduce the y-axis from 1million cells to 100 cells. 

Do you think it could be done? 

I think I was able to fit a model, but I got stuck projecting the original spike raster plot back into the reduced dimension space.

**Comment by kokitsuyuzaki** [comment]
I think you can do it.
As long as the data is a CSV file with no row or column names, you should be able to run the Online PCA as in the README.md example.
https://github.com/rikenbit/OnlinePCA.jl#preprocess-of-csv
